-- BP-015 — Generated seed data for production_people.
--
-- GENERATED FILE — do not hand-edit. Produced by `npm run db:generate-seed`
-- (scripts/generate-supabase-seed.ts) from src/features/people/data.ts.
-- Re-run the generator to regenerate after data.ts changes.
--
-- Generated: 2026-08-04T19:41:10.779Z
-- Records: 36
--
-- Run this in the Supabase SQL Editor after supabase/migrations/0001_create_production_people.sql.
-- Safe to re-run: each row is upserted by id.
insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-peter-berns', '2026-07-22T16:29:00.000Z', '2026-07-22T16:29:00.000Z', 'current', 'Peter', NULL, 'Berns', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-aidan-borosko', '2026-07-30T14:29:00.000Z', '2026-07-30T14:29:00.000Z', 'current', 'Aidan', NULL, 'Borosko', NULL, '2006-03-07', NULL, '(973) 722-8424', NULL, 'borosk_a1@denison.edu', NULL, NULL, NULL, 'Monclair', 'NJ', NULL, 'USA', 2029, NULL, NULL, 'D02008078', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-jp-boyle', '2023-01-01T08:47:00.000Z', '2023-01-01T08:47:00.000Z', 'current', 'JP', NULL, 'Boyle', NULL, '2003-11-28', NULL, '(631) 561-1552', NULL, 'boyle_j1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2029, NULL, NULL, 'D01945130', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'inactive', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-jack-bulger', '2024-01-25T07:11:00.000Z', '2024-01-25T07:11:00.000Z', 'alumni', 'Jack', NULL, 'Bulger', NULL, '2001-07-23', NULL, '(415) 745-5999', NULL, 'bulger_j1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Mathmatics', NULL, 'D01919515', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-andreas-chapides', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Andreas', NULL, 'Chapides', NULL, '2003-03-21', NULL, '(614) 989-7544', NULL, 'chapid_a1@denison.edu', NULL, NULL, NULL, 'Limassol', NULL, NULL, 'Cyprus', NULL, 'HESS', 'Global Commerce', 'D01958406', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-luke-colson', '2026-07-22T16:28:00.000Z', '2026-07-22T16:28:00.000Z', 'current', 'Luke', NULL, 'Colson', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-mason-conlin', '2026-07-22T10:00:00.000Z', '2026-07-22T10:00:00.000Z', 'current', 'Mason', 'Jonathon Mason (Mason is middle name)', 'Conlin', NULL, '2005-12-24', NULL, '(510) 571-9884', NULL, 'conlin_m1@denison.edu', NULL, NULL, NULL, 'Almeda', 'CA', NULL, 'USA', 2028, NULL, NULL, 'D01992157', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-blake-eason', '2023-02-06T10:14:00.000Z', '2023-02-06T10:14:00.000Z', 'current', 'Blake', NULL, 'Eason', NULL, '2002-10-01', NULL, '(702) 249-9104', NULL, 'eason_b1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2029, 'Economics', NULL, 'D01929597', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'inactive', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-camden-french', '2024-01-25T07:12:00.000Z', '2024-01-25T07:12:00.000Z', 'current', 'Camden', NULL, 'French', NULL, '2003-09-26', NULL, '(858) 281-8113', NULL, 'french_c1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2029, NULL, NULL, 'D01958471', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'inactive', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-arya-ganapathy-kallambella', '2026-07-23T09:39:00.000Z', '2026-07-23T09:39:00.000Z', 'current', 'Arya', NULL, 'Ganapathy Kallambella', NULL, '2007-01-21', NULL, '(423) 309-1442', NULL, 'kallam_a1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, 'India', 2029, NULL, NULL, 'D02012161', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-daniel-garcia', '2024-01-25T07:11:00.000Z', '2024-01-25T07:11:00.000Z', 'alumni', 'Daniel', NULL, 'Garcia', NULL, '2001-07-16', NULL, '(740) 348-9088', NULL, 'garcia_d2@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Economics', 'Global Commerce', 'D01936816', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-milan-gonela', '2026-05-23T06:23:00.000Z', '2026-05-23T06:23:00.000Z', 'alumni', 'Milan', NULL, 'Gonela', NULL, '2001-10-26', NULL, '(614) 558-6169', NULL, 'gonela_m1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HESS', NULL, 'D01931296', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-colin-gramley', '2025-07-16T14:24:00.000Z', '2025-07-16T14:24:00.000Z', 'alumni', 'Colin', 'Connor', 'Gramley', NULL, '2002-07-09', NULL, '(724) 866-4008', NULL, 'gramle_c1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Economics', NULL, 'D01943275', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-ethan-green', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Ethan', 'Michael', 'Green', NULL, '2004-05-17', NULL, '(385) 441-2374', NULL, 'green_e1@denison.edu', NULL, NULL, NULL, 'Salt Lake City', 'UT', NULL, 'USA', NULL, 'Financial Economics', NULL, 'D01960444', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-marc-lennart-harms', '2024-01-25T07:11:00.000Z', '2024-01-25T07:11:00.000Z', 'alumni', 'Marc-Lennart', NULL, 'Harms', NULL, '2000-03-21', NULL, '(740) 405-8645', NULL, 'harms_m1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Economics', 'Global Commerce', 'D01936964', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-wesley-huang', '2026-07-22T17:59:00.000Z', '2026-07-22T17:59:00.000Z', 'current', 'Wesley', NULL, 'Huang', NULL, '2006-12-18', NULL, '(626) 714-9190', NULL, 'Huang_w1@denison.edu', NULL, NULL, NULL, 'Pasedena', 'CA', NULL, 'USA', 2029, NULL, NULL, 'D02009316', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-balraj-idnani', '2026-07-22T07:19:00.000Z', '2026-07-22T07:19:00.000Z', 'current', 'Balraj', NULL, 'Idnani', NULL, '2006-07-20', NULL, '(551) 502-2612', NULL, 'idnani_b1@denison.edu', NULL, NULL, NULL, 'Park Ridge', 'NJ', NULL, 'USA', 2029, NULL, NULL, 'D02010280', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-ishwar-idnani', '2026-07-22T08:57:00.000Z', '2026-07-22T08:57:00.000Z', 'current', 'Ishwar', NULL, 'Idnani', NULL, '2006-07-20', NULL, '(551) 502-3037', NULL, 'idnani_i1@denison.edu', NULL, NULL, NULL, 'Park Ridge', 'NJ', NULL, 'USA', 2029, NULL, NULL, 'D02010256', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-nadeem-jones', '2024-07-14T09:20:00.000Z', '2024-07-14T09:20:00.000Z', 'alumni', 'Nadeem', NULL, 'Jones', NULL, '2002-08-08', NULL, '(304) 993-1347', NULL, 'jones_n1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Art Studio', 'Biology', 'D01929597', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-aayush-kishore', '2025-02-05T19:29:00.000Z', '2025-02-05T19:29:00.000Z', 'current', 'Aayush', NULL, 'Kishore', NULL, '2004-11-12', NULL, '(908) 848-7090', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2029, 'Psychology', NULL, 'D02002741', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'inactive', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-minato-koido', '2026-07-22T16:38:00.000Z', '2026-07-22T16:38:00.000Z', 'current', 'Minato', NULL, 'Koido', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-andy-mackler', '2026-01-08T06:43:00.000Z', '2026-01-08T06:43:00.000Z', 'alumni', 'Andy', NULL, 'Mackler', NULL, '2001-09-28', NULL, '(407) 994-3266', NULL, 'mackle_a1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HESS', 'Global Health', 'D01926981', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-jackson-mactaggart', '2026-07-22T18:05:00.000Z', '2026-07-22T18:05:00.000Z', 'current', 'Jackson', NULL, 'MacTaggart', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2030, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-dimitrio-martinez', '2024-01-25T07:11:00.000Z', '2024-01-25T07:11:00.000Z', 'alumni', 'Dimitrio', NULL, 'Martinez', NULL, '1982-10-04', NULL, '(305) 905-3427', NULL, 'martinezd@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-nick-meyers', '2026-07-22T16:54:00.000Z', '2026-07-22T16:54:00.000Z', 'current', 'Nick', 'Petar', 'Meyers', NULL, '2005-10-11', NULL, '(513) 390-2678', NULL, 'meyers_n2@denison.edu', NULL, NULL, NULL, 'Cincinnati', 'OH', NULL, 'USA', 2028, 'Financial Economics', NULL, 'D01993403', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-nickawn-namdar', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Nickawn', NULL, 'Namdar', NULL, '2004-01-08', NULL, '(415) 910-2600', NULL, 'namdar_n1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pre Med', NULL, 'D01959677', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-chika-nwaozuzu', '2026-07-30T14:29:00.000Z', '2026-07-30T14:29:00.000Z', 'current', 'Chika', 'Janez Caleb', 'Nwaozuzu', NULL, '2006-10-25', NULL, '(216) 556-3220', NULL, 'nwaozu_c1@denison.edu', NULL, NULL, NULL, 'Cleveland', 'OH', NULL, 'USA', 2028, 'Economics', NULL, 'D01994492', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-tomer-ozmo', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Tomer', NULL, 'Ozmo', NULL, '2001-06-28', NULL, NULL, NULL, 'osmo_t1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Computer Science', NULL, 'D01958604', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-kyle-patrick', '2026-07-22T08:54:00.000Z', '2026-07-22T08:54:00.000Z', 'current', 'Kyle', 'Liam', 'Patrick', NULL, '2004-09-02', NULL, '(203) 253-8758', NULL, 'patric_k1@denison.edu', NULL, NULL, NULL, 'Darien', 'CT', NULL, 'USA', 2027, 'Economics', NULL, 'D01976432', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-ryan-patrick', '2025-07-16T14:24:00.000Z', '2025-07-16T14:24:00.000Z', 'alumni', 'Ryan', 'Edward', 'Patrick', NULL, '2002-10-28', NULL, '(203) 858-5982', NULL, 'patric_r2@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Economics', NULL, 'D01945494', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-jake-patterson', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Jake', 'Robert', 'Patterson', NULL, '2004-02-03', NULL, '(412) 888-7114', NULL, 'patter_j2@denison.edu', NULL, NULL, NULL, 'Bridgeville', 'PA', NULL, 'USA', NULL, 'Global Commerce', NULL, 'D01958612', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-anthony-payiavlas', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Anthony', 'John', 'Payiavlas', NULL, '2004-02-02', NULL, '(330) 646-9533', NULL, 'payiav_a1@denison.edu', NULL, NULL, NULL, 'Warren', 'OH', NULL, 'USA', NULL, 'Communication', NULL, 'D01959370', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-zach-portnoy', '2024-07-14T09:20:00.000Z', '2024-07-14T09:20:00.000Z', 'alumni', 'Zach', NULL, 'Portnoy', NULL, '2001-01-09', NULL, '(347) 406-0819', NULL, 'portno_z1@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'HESS', NULL, 'D01971136', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-kael-shah', '2026-05-23T06:26:00.000Z', '2026-05-23T06:26:00.000Z', 'alumni', 'Kael', 'Shalin', 'Shah', NULL, '2003-08-25', NULL, '(740) 403-6456', NULL, 'shah_k1@denison.edu', NULL, NULL, NULL, 'Nairobi', NULL, NULL, 'Kenya', NULL, NULL, NULL, 'D01975269', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-tom-suedmeyer', '2026-07-22T14:36:00.000Z', '2026-07-22T14:36:00.000Z', 'current', 'Tom', NULL, 'Suedmeyer', NULL, '2005-09-04', NULL, '(740) 323-7691', 'suedmeyer.tom@gmail.com', NULL, NULL, NULL, NULL, 'Dusseldorf', NULL, NULL, 'Germany', 2029, NULL, NULL, 'D01993999', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'active', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;

insert into public.production_people (id, created_at, updated_at, status, first_name, middle_name, last_name, preferred_name, date_of_birth, photo_url, cell_phone, personal_email, denison_email, preferred_contact_method, address_line1, address_line2, city, state, zip_code, country, class_year, major, minor, denison_id, dorm, room_number, utr, wtn, dominant_hand, height_inches, weight_lbs, player_status, relationships, notes)
values ('player-archie-turner', '2025-07-16T14:24:00.000Z', '2025-07-16T14:24:00.000Z', 'alumni', 'Archie', 'Joseph', 'Turner', NULL, '2002-05-12', NULL, NULL, NULL, 'graham_a2@denison.edu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Economics', NULL, 'D01943689', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'graduated', '[]'::jsonb, NULL)
on conflict (id) do update set
  created_at = excluded.created_at,
    updated_at = excluded.updated_at,
    status = excluded.status,
    first_name = excluded.first_name,
    middle_name = excluded.middle_name,
    last_name = excluded.last_name,
    preferred_name = excluded.preferred_name,
    date_of_birth = excluded.date_of_birth,
    photo_url = excluded.photo_url,
    cell_phone = excluded.cell_phone,
    personal_email = excluded.personal_email,
    denison_email = excluded.denison_email,
    preferred_contact_method = excluded.preferred_contact_method,
    address_line1 = excluded.address_line1,
    address_line2 = excluded.address_line2,
    city = excluded.city,
    state = excluded.state,
    zip_code = excluded.zip_code,
    country = excluded.country,
    class_year = excluded.class_year,
    major = excluded.major,
    minor = excluded.minor,
    denison_id = excluded.denison_id,
    dorm = excluded.dorm,
    room_number = excluded.room_number,
    utr = excluded.utr,
    wtn = excluded.wtn,
    dominant_hand = excluded.dominant_hand,
    height_inches = excluded.height_inches,
    weight_lbs = excluded.weight_lbs,
    player_status = excluded.player_status,
    relationships = excluded.relationships,
    notes = excluded.notes;
