import Link from "next/link";
import Image from "next/image";
import { ArrowRight, CalendarDays, ChartNoAxesCombined, CircleGauge, MessageCircle, Trophy } from "lucide-react";
import ModulePageShell from "@/components/ModulePageShell";
import type { RecruitInteraction } from "@/features/interactions/types";
import { interactionTypeLabel } from "@/features/interactions/whatsappNotes";
import type { UpcomingDashboardVisit } from "@/features/recruiting/dashboard";
import type { RecentUtrRecruitResult } from "@/features/recruiting/todayBeta/repository";
import { recruitingPersonCommunicationsPath, recruitingPersonVisitPath } from "@/lib/module-routes";
import { dayRulePercent, sparklinePointsInRange } from "./dashboardMath";
type Elo={id:string;name:string;rating:number;history:number[]};type Match={id:string;date:string;score:string;winner:string;loser:string;unfinished:boolean};type Tone="red"|"blue"|"violet"|"orange";
type MonthRule={label:string;used:number;budget:number};type Event={id:string;name:string;date:string;location:string;logoSrc:string|null;initials:string};
const eloColors=["#fb7185","#60a5fa","#a78bfa","#34d399","#fbbf24"];
const date=(v:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(`${v.slice(0,10)}T12:00:00`));const initials=(n:string)=>n.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
function Header({title,href,label,tone,icon:Icon}:{title:string;href:string;label:string;tone:Tone;icon:typeof Trophy}){return <div className={`hd-header hd-${tone}`}><div className="hd-heading"><span className="hd-icon"><Icon size={16}/></span><h2 className="hd-title">{title}</h2></div><Link className="hd-more" href={href}>{label}<ArrowRight size={12}/></Link></div>};function Card({children}:{children:React.ReactNode}){return <section className="hd-card">{children}</section>}function Empty({children}:{children:React.ReactNode}){return <div className="hd-empty">{children}</div>}
function EloCard({rows}:{rows:Elo[]}){const series=rows.map(r=>r.history.length?[1500,...r.history]:[r.rating]);const all=series.flat();const min=Math.min(...all)-8,max=Math.max(...all)+8;return <Card><Header title="Team · Top 5 Elo" href="/team-operations/intra-squad?tab=elo" label="Full rankings" tone="violet" icon={ChartNoAxesCombined}/>{!rows.length?<Empty>No Elo rankings yet.</Empty>:<div className="hd-eloBody"><div className="hd-chart"><div className="hd-chartTop"><div><p className="hd-eyebrow">Top 5 rating trends</p><p className="hd-chartName">Shared Elo scale</p></div><strong className="hd-rating">{rows[0]!.rating}</strong></div><svg viewBox="0 0 420 92" className="hd-chartSvg"><path d="M0 22H420M0 48H420M0 74H420" stroke="#344159"/>{series.map((values,i)=><polyline key={rows[i]!.id} points={sparklinePointsInRange(values,min,max)} fill="none" stroke={eloColors[i]} strokeWidth={i===0?4:2.5} strokeLinecap="round" strokeLinejoin="round"/>)}</svg><div className="hd-legend">{rows.map((r,i)=><span className="hd-legendItem" key={r.id}><i className="hd-dot" style={{background:eloColors[i]}}/>{r.name}</span>)}</div></div><div className="hd-rankings">{rows.slice(0,5).map((r,i)=><div className="hd-ranking" key={r.id}><span className={`hd-rank ${i===0?"hd-first":""}`} style={{borderBottom:`2px solid ${eloColors[i]}`}}>{i+1}</span><div className="hd-copy"><p className="hd-primary">{r.name}</p><p className="hd-secondary">{r.history.length} rated {r.history.length===1?"match":"matches"}</p></div><strong className="hd-value">{r.rating}</strong></div>)}</div></div>}</Card>}
function Practice({month}:{month:MonthRule|null}){const pct=month?dayRulePercent(month.used,month.budget):0;return <Card><Header title="Practice · 114-Day Rule" href="/team-operations/practice?tab=114-day-tracker" label="Tracker" tone="orange" icon={CircleGauge}/>{!month?<Empty>Current-month practice budget unavailable.</Empty>:<div className="hd-practice"><div className="hd-ring" style={{background:`conic-gradient(#f59e0b ${pct}%,#e7e9ee 0)`}}><div className="hd-ringCenter"><strong className="hd-ringValue">{month.used}</strong><span className="hd-ringLabel">of {month.budget}</span></div></div><div className="hd-copy"><p className="hd-practiceTitle">{month.label}</p><p className="hd-practiceText">{month.used} days used · {month.budget} day budget</p><p className="hd-remaining">{Math.max(month.budget-month.used,0)} budgeted days remaining this month</p></div></div>}</Card>}
function Activity({rows}:{rows:RecruitInteraction[]}){return <Card><Header title="Recruiting · Recent Activity" href="/recruiting" label="Recruiting" tone="red" icon={MessageCircle}/>{!rows.length?<Empty>No recent recruiting interactions.</Empty>:<div className="hd-list">{rows.map(r=><Link className="hd-row" key={r.id} href={recruitingPersonCommunicationsPath(r.recruitPersonId)}><span className="hd-avatar">{initials(r.recruitName)}</span><div className="hd-copy"><p className="hd-primary">{r.recruitName} · {interactionTypeLabel(r.interactionType,r.sourceSystem)}</p><p className="hd-secondary">{r.notes||r.nextSteps||r.direction?.replace("_"," ")||"Interaction logged"}</p></div><time className="hd-secondary">{date(r.occurredAt)}</time></Link>)}</div>}</Card>}
function Visits({rows}:{rows:UpcomingDashboardVisit[]}){return <Card><Header title="Recruiting · Upcoming Visits" href="/recruiting" label="Visits" tone="blue" icon={CalendarDays}/>{!rows.length?<Empty>No upcoming visits scheduled.</Empty>:<div className="hd-list">{rows.map(r=><Link className="hd-row" key={`${r.personId}-${r.visitStartDate}`} href={recruitingPersonVisitPath(r.personId)}><span className="hd-date"><span className="hd-dateMonth">{new Date(`${r.visitStartDate}T12:00:00`).toLocaleString("en-US",{month:"short"})}</span><strong className="hd-dateDay">{Number(r.visitStartDate.slice(-2))}</strong></span><div className="hd-copy"><p className="hd-primary">{r.name}</p><p className="hd-secondary">{date(r.visitStartDate)}–{date(r.visitEndDate)}{r.travelType?` · ${r.travelType}`:""}</p></div>{r.dayCount?<span className="hd-value">{r.dayCount}d</span>:null}</Link>)}</div>}</Card>}
function Matches({rows}:{rows:Match[]}){return <Card><Header title="Team Matches · Last 5" href="/team-operations/intra-squad?tab=match-log" label="Results" tone="violet" icon={Trophy}/>{!rows.length?<Empty>No match results recorded.</Empty>:<div className="hd-list">{rows.map(r=><div className="hd-row" key={r.id}><span className="hd-teamLogo"><Image src="/school-logos/Denison_transparent.png" alt="Denison" width={28} height={28}/></span><div className="hd-copy"><p className="hd-primary">{r.winner} def. {r.loser}</p><p className="hd-secondary">{date(r.date)}{r.unfinished?" · Unfinished":""}</p></div><span className="hd-score">{r.score||"Result"}</span></div>)}</div>}</Card>}
function UtrResults({rows}:{rows:RecentUtrRecruitResult[]}){return <Card><Header title="Recruiting · Last 5 UTR Results" href="/recruiting/today-beta" label="Today Beta" tone="red" icon={Trophy}/>{!rows.length?<Empty>No UTR match results have been imported.</Empty>:<div className="hd-list">{rows.map(r=><Link className="hd-row" key={r.id} href={recruitingPersonCommunicationsPath(r.recruitPersonId)}><span className="hd-avatar">{initials(r.recruitName)}</span><div className="hd-copy"><p className="hd-primary">{r.recruitName} <span className="hd-secondary">vs. {r.opponentName||"Opponent"}</span></p><p className="hd-secondary">{r.tournamentDate?date(r.tournamentDate):"Date unavailable"}{r.tournamentName?` · ${r.tournamentName}`:""}</p></div><span className={`hd-result ${r.result==="WIN"?"hd-win":"hd-loss"}`}>{r.result}{r.score?` · ${r.score}`:""}</span></Link>)}</div>}</Card>}
function Events({rows}:{rows:Event[]}){return <Card><Header title="Team Schedule · Next 3 Events" href="/team-operations/schedule" label="Schedule" tone="blue" icon={CalendarDays}/>{!rows.length?<Empty>No upcoming schedule events.</Empty>:<div className="hd-list">{rows.map(r=><Link className="hd-row" key={r.id} href="/team-operations/schedule"><span className="hd-eventLogo">{r.logoSrc?<Image src={r.logoSrc} alt="" width={34} height={34}/>:r.initials}</span><div className="hd-copy"><p className="hd-primary">{r.name}</p><p className="hd-secondary">{date(r.date)} · {r.location}</p></div></Link>)}</div>}</Card>}
export default function HomeDashboard({elo,matches,interactions,visits,utrResults,monthRule,events}:{elo:Elo[];matches:Match[];interactions:RecruitInteraction[];visits:UpcomingDashboardVisit[];utrResults:RecentUtrRecruitResult[];monthRule:MonthRule|null;events:Event[]}){return <ModulePageShell title="Dashboard" subtitle="Your Denison Tennis command center"><div className="hd-grid"><div className="hd-column"><EloCard rows={elo}/><UtrResults rows={utrResults}/><Activity rows={interactions}/></div><div className="hd-column"><Practice month={monthRule}/><Events rows={events}/><Visits rows={visits}/><Matches rows={matches}/></div></div></ModulePageShell>}
