"use client";
import { ArrowDown, ArrowLeft, ArrowUp, BellRing, CalendarCheck2, Clock3, GripVertical, MapPin, Pencil, Plus, Search, Sparkles, X } from "lucide-react";
import { useRouter } from "next/navigation";
import type { PointerEvent as ReactPointerEvent } from "react";
import { useState, useTransition } from "react";
import { saveDailyPlanAction } from "../actions";
import { moveItem } from "../reorder";
import type { DailyPracticePlan, DayRuleSummary, PracticeDrill } from "../types";
import styles from "./dailyPlanBuilder.module.css";

const field = "h-10 w-full rounded-control border border-border bg-white px-3 text-sm outline-none focus:border-[var(--module-accent)]";

function signed(value: number) { return value > 0 ? `+${value}` : String(value); }

function PlanDayRuleSummary({ plan, summary }: { plan: DailyPracticePlan; summary: DayRuleSummary }) {
  const month = Number(plan.planDate.slice(5, 7));
  const year = Number(plan.planDate.slice(0, 4));
  const day = Number(plan.planDate.slice(8, 10));
  const rowIndex = summary.rows.findIndex((row) => row.month === month);
  const row = summary.rows[rowIndex];
  const counted = row?.days.some((item) => item.date === plan.planDate) ?? plan.countable;
  const daysInMonth = new Date(year, month, 0).getDate();
  const budgetToPlanDate = rowIndex < 0 ? 0 : summary.rows.slice(0, rowIndex).reduce((sum, item) => sum + item.budget, 0) + Math.round(row.budget * day / daysInMonth);
  const seasonStartYear = month >= 8 ? year : year - 1;
  const seasonStart = `${seasonStartYear}-08-01`;
  const usedToPlanDate = new Set(summary.rows.flatMap((item) => item.days.map((countedDay) => countedDay.date)).filter((date) => date >= seasonStart && date <= plan.planDate)).size;
  const toDateVariance = budgetToPlanDate - usedToPlanDate;
  const monthVariance = row ? row.budget - row.used : 0;
  const seasonUsed = summary.used;
  return <div className="mb-4 grid gap-2" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(135px, 1fr))" }}>
    <Metric label="This date" value={counted ? "Counted" : "Not counted"} detail={counted ? "1 day toward 114" : "0 days toward 114"} tone={counted ? "green" : "slate"}/>
    <Metric label={row?.label ?? "Month"} value={`${row?.used ?? 0} / ${row?.budget ?? 0}`} detail={`${signed(monthVariance)} to monthly budget`} tone={monthVariance < 0 ? "red" : "blue"}/>
    <Metric label="Season total" value={`${seasonUsed} / ${summary.limit}`} detail={`${summary.remaining} days remaining`} tone={summary.remaining < 0 ? "red" : "violet"}/>
    <Metric label="Budget to this date" value={`${usedToPlanDate} / ${budgetToPlanDate}`} detail={`${signed(toDateVariance)} to date · positive is under`} tone={toDateVariance < 0 ? "red" : "green"}/>
  </div>;
}

function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: "green" | "blue" | "violet" | "red" | "slate" }) {
  const colors = { green: "border-emerald-200 bg-emerald-50 text-emerald-900", blue: "border-blue-200 bg-blue-50 text-blue-900", violet: "border-violet-200 bg-violet-50 text-violet-900", red: "border-red-200 bg-red-50 text-red-900", slate: "border-slate-200 bg-slate-50 text-slate-700" };
  return <div className={`rounded-control border p-3 ${colors[tone]}`}><p className="text-[9px] font-bold tracking-wider uppercase opacity-70">{label}</p><p className="mt-1 text-lg font-bold tabular-nums">{value}</p><p className="mt-0.5 text-[10px] font-medium opacity-75">{detail}</p></div>;
}

export default function DailyPlanBuilder({ drills, plans, dayRule, initialPlanId = null, initialPlanDate = null }: { drills: PracticeDrill[]; plans: DailyPracticePlan[]; dayRule: DayRuleSummary; initialPlanId?: string | null; initialPlanDate?: string | null }) {
  const router = useRouter();
  const todayParts = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date());
  const todayPart = (type: Intl.DateTimeFormatPartTypes) => todayParts.find((part) => part.type === type)?.value ?? "";
  const today = `${todayPart("year")}-${todayPart("month")}-${todayPart("day")}`;
  const todayPlan = plans.find((plan) => plan.planDate === today);
  const previousPlans = plans.filter((plan) => plan.planDate < today);
  const [activePlanId, setActivePlanId] = useState<string | null>(initialPlanId);
  const current = activePlanId ? plans.find((plan) => plan.id === activePlanId) : initialPlanDate ? plans.find((plan) => plan.planDate === initialPlanDate) : todayPlan;
  const [editing, setEditing] = useState(Boolean(initialPlanDate)); const [selected, setSelected] = useState<string[]>(current?.drills.map((drill) => drill.id) ?? []); const [draggingId, setDraggingId] = useState<string | null>(null); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition();
  const selectedDrills = selected.map((id) => drills.find((drill) => drill.id === id)).filter((drill): drill is PracticeDrill => Boolean(drill));
  const availableDrills = drills.filter((drill) => !selected.includes(drill.id) && [drill.name, drill.description, drill.tags.join(" ")].join(" ").toLowerCase().includes(query.trim().toLowerCase()));
  function beginEditing(plan: DailyPracticePlan) { setMessage(""); setSelected(plan.drills.map((drill) => drill.id)); setEditing(true); }
  function backToNewPlan() { setActivePlanId(null); setSelected(todayPlan?.drills.map((drill) => drill.id) ?? []); setEditing(false); }
  function moveDrill(index: number, direction: -1 | 1) { setSelected((value) => moveItem(value, index, index + direction)); }
  function startDrag(id: string, event: ReactPointerEvent<HTMLButtonElement>) { event.currentTarget.setPointerCapture(event.pointerId); setDraggingId(id); }
  function updateDrag(id: string, event: ReactPointerEvent<HTMLButtonElement>) { if (draggingId !== id) return; const row = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-drill-index]"); const target = Number(row?.dataset.drillIndex); if (!Number.isInteger(target)) return; setSelected((value) => moveItem(value, value.indexOf(id), target)); }
  function finishDrag(event: ReactPointerEvent<HTMLButtonElement>) { if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); setDraggingId(null); }
  const history = <aside className="rounded-card border border-border bg-surface p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Previous Plans</h2><p className="text-xs text-text-secondary">Open or edit an earlier practice.</p></div><CalendarCheck2 className="h-5 w-5 text-violet-600"/></div><div className="mt-3 max-h-[30rem] space-y-2 overflow-y-auto">{previousPlans.length ? previousPlans.map((plan) => <button type="button" key={plan.id} onClick={() => { setActivePlanId(plan.id); setSelected(plan.drills.map((drill) => drill.id)); setEditing(false); }} className={`w-full rounded-control border p-3 text-left transition ${current?.id === plan.id ? "border-violet-400 bg-violet-50" : "border-border hover:border-violet-200 hover:bg-app-background"}`}><span className="block text-[10px] font-semibold tracking-wide text-text-secondary uppercase">{plan.planDate}</span><span className="mt-1 block text-sm font-semibold">{plan.title}</span><span className="mt-1 block text-[11px] text-text-secondary">{plan.drills.length} drills · {plan.countable ? "Countable" : "Non-countable"}</span></button>) : <p className="rounded-control bg-app-background px-3 py-6 text-center text-xs text-text-secondary">No previous plans yet.</p>}</div></aside>;
  if (!editing && !current) return <div className="grid gap-3 lg:grid-cols-[1.45fr_0.75fr]"><section className="relative overflow-hidden rounded-card border border-violet-300 p-8 text-white shadow-[0_18px_45px_rgba(79,70,229,0.22)] sm:p-10" style={{ background: "linear-gradient(135deg, #6d28d9 0%, #4338ca 55%, #0284c7 100%)" }}><div className="absolute -top-20 -right-16 h-56 w-56 rounded-full bg-white/10"/><div className="relative max-w-2xl"><span className="inline-flex h-11 w-11 items-center justify-center rounded-xl bg-white/15"><Sparkles className="h-5 w-5"/></span><p className="mt-5 text-xs font-semibold tracking-widest text-indigo-100 uppercase">Today · {today}</p><h2 className="mt-2 text-2xl font-semibold sm:text-3xl">Build Today’s Plan</h2><p className="mt-3 max-w-xl text-sm leading-6 text-indigo-100">No plan has been created for today. Set the schedule, announcements, drills, and countable-date status.</p><button type="button" onClick={() => { setActivePlanId(null); setSelected([]); setEditing(true); }} className="mt-6 inline-flex h-11 items-center gap-2 rounded-control bg-white px-5 text-sm font-semibold text-indigo-700 shadow-lg transition hover:-translate-y-0.5"><Plus className="h-4 w-4"/>Build Today’s Plan</button></div></section>{history}</div>;
  if (!editing && current) return <div className="grid gap-3">
    {activePlanId ? <button type="button" onClick={backToNewPlan} className="inline-flex w-fit shrink-0 items-center gap-1.5 text-sm font-medium text-text-secondary transition-colors duration-150 hover:text-text-primary"><ArrowLeft className="h-4 w-4" strokeWidth={1.75}/>Back to New Plan</button> : null}
    <div className={styles.savedLayout}>
    <section className="overflow-hidden rounded-card border border-violet-200 bg-surface shadow-[0_12px_30px_rgba(124,58,237,0.08)]"><div className="p-4 text-white" style={{ background: "linear-gradient(90deg, #6d28d9, #4f46e5)" }}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-semibold tracking-wider text-violet-100 uppercase">{current.planDate === today ? "Today’s Plan" : "Previous Plan"} · {current.planDate}</p><h2 className="mt-1 text-xl font-semibold">{current.title}</h2><p className="mt-1 text-xs text-violet-100">{current.startTime || "Time TBD"}{current.endTime ? `–${current.endTime}` : ""} · {current.location || "Location TBD"}</p></div><button type="button" onClick={() => beginEditing(current)} className="inline-flex h-9 items-center gap-1.5 rounded-control bg-white px-3 text-xs font-semibold text-violet-700"><Pencil className="h-3.5 w-3.5"/>Edit Plan</button></div></div><div className="p-5"><PlanDayRuleSummary plan={current} summary={dayRule}/><div className="mb-4 rounded-control border border-amber-200 bg-amber-50 p-3"><div className="flex items-center gap-2 text-xs font-semibold text-amber-900"><BellRing className="h-4 w-4"/>Team Announcements</div><p className="mt-1.5 whitespace-pre-wrap text-sm text-amber-950">{current.announcements || "No announcements."}</p></div><h3 className="text-xs font-semibold tracking-wide text-text-secondary uppercase">Practice sequence</h3><div className="mt-2 space-y-2">{current.drills.length ? current.drills.map((drill, index) => <div key={drill.id} className="flex items-start gap-3 rounded-control border border-border p-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">{index + 1}</span><div><p className="text-sm font-semibold">{drill.name}</p><p className="mt-0.5 text-xs text-text-secondary">{drill.description || drill.tags.join(" · ")}</p></div></div>) : <p className="text-sm text-text-secondary">No drills selected.</p>}</div></div></section>
    <div className="grid content-start gap-3"><button type="button" onClick={() => beginEditing(current)} className="inline-flex h-11 items-center justify-center gap-2 rounded-control bg-[var(--module-accent)] px-4 text-sm font-semibold text-white shadow-sm"><Pencil className="h-4 w-4"/>Edit This Plan</button><div className="grid grid-cols-[auto_1fr] items-start gap-3"><div className="inline-flex min-h-16 items-center gap-2 rounded-card px-3 py-2 text-white shadow-sm" style={{ background: "#059669" }}><CalendarCheck2 className="h-4 w-4"/><span className="text-xs font-semibold">{current.countable ? "Countable" : "Non-countable"}</span></div><div className="min-h-16 rounded-card border border-sky-200 bg-sky-50 p-3"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-sky-600"/><p className="text-xs font-semibold">Practice Focus</p></div><p className="mt-1 text-xs leading-5 text-text-secondary">{current.focus || "No focus entered."}</p></div></div>{history}</div>
    </div>
  </div>;
  return <form className="grid gap-3 lg:grid-cols-[1.15fr_0.95fr]" action={(formData) => startTransition(async () => { const result = await saveDailyPlanAction(formData); setMessage(result.success ? "Plan saved." : `Could not save: ${result.message}`); if (result.success) { router.refresh(); setEditing(false); } })}>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-card border border-violet-200 bg-surface px-4 py-3 shadow-sm lg:col-span-2"><div><p className="text-[10px] font-bold tracking-wider text-violet-700 uppercase">{current ? `Editing ${current.planDate}` : "New daily plan"}</p><p className="mt-0.5 text-sm font-semibold text-text-primary">{current ? current.title : "Build Today’s Plan"}</p></div><div className="flex items-center gap-2">{current ? <button type="button" onClick={() => setEditing(false)} className="h-10 rounded-control border border-border bg-surface px-4 text-sm font-semibold hover:bg-app-background">Cancel</button> : null}<button type="submit" disabled={pending} className="inline-flex h-10 items-center gap-2 rounded-control bg-[var(--module-accent)] px-5 text-sm font-semibold text-white shadow-sm disabled:opacity-60">{pending ? "Saving…" : current ? "Save Changes" : "Save Plan"}</button></div></div>
    <section className="rounded-card border border-violet-200 bg-gradient-to-br from-violet-50 via-white to-indigo-50 p-5 shadow-sm"><div className="flex items-center gap-2 text-violet-700"><Sparkles className="h-5 w-5"/><h2 className="text-base font-semibold">Build Daily Plan</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Date<input required name="planDate" type="date" defaultValue={current?.planDate ?? initialPlanDate ?? new Date().toISOString().slice(0,10)} className={`${field} mt-1`}/></label><label className="text-xs font-semibold">Title<input name="title" defaultValue={current?.title ?? "Team Practice"} className={`${field} mt-1`}/></label><label className="text-xs font-semibold"><Clock3 className="mr-1 inline h-3.5 w-3.5"/>Start<input name="startTime" type="time" defaultValue={current?.startTime ?? "14:45"} className={`${field} mt-1`}/></label><label className="text-xs font-semibold">End<input name="endTime" type="time" defaultValue={current?.endTime ?? "17:00"} className={`${field} mt-1`}/></label><label className="text-xs font-semibold sm:col-span-2"><MapPin className="mr-1 inline h-3.5 w-3.5"/>Location<input name="location" defaultValue={current?.location ?? "Mitchell Center Courts"} className={`${field} mt-1`}/></label><label className="text-xs font-semibold sm:col-span-2">Practice focus<textarea name="focus" defaultValue={current?.focus} rows={2} className={`${field} mt-1 h-auto py-2`}/></label><label className="text-xs font-semibold sm:col-span-2"><BellRing className="mr-1 inline h-3.5 w-3.5"/>Team announcements<textarea name="announcements" defaultValue={current?.announcements} rows={3} className={`${field} mt-1 h-auto py-2`}/></label></div><label className="mt-4 flex items-center gap-3 rounded-control border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-900"><input name="countable" type="checkbox" defaultChecked={current?.countable ?? true} className="h-4 w-4 accent-emerald-600"/>Count this date toward the 114-day rule</label><input type="hidden" name="status" value="published"/><div className="mt-4 flex flex-wrap items-center gap-2"><button type="submit" disabled={pending} className="h-10 rounded-control bg-violet-700 px-5 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving…" : current ? "Save Changes" : "Save Plan"}</button>{current ? <button type="button" onClick={() => setEditing(false)} className="h-10 rounded-control border border-border px-4 text-sm font-semibold">Cancel</button> : null}<span className="text-xs text-text-secondary">{message}</span></div></section>
    <section className="rounded-card border border-sky-200 bg-surface p-4 shadow-sm">
      {selected.map((id) => <input key={id} type="hidden" name="drillIds" value={id}/>)}
      <div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Practice Sequence</h2><p className="text-xs text-text-secondary">{selected.length} selected · drag the handle to reorder</p></div><Plus className="h-5 w-5 text-sky-600"/></div>
      <div className="mt-3 space-y-2">{selectedDrills.map((drill, index) => <div key={drill.id} data-drill-index={index} className={`flex items-center gap-2 rounded-control border p-2.5 transition ${draggingId === drill.id ? "scale-[1.01] border-violet-500 bg-white shadow-lg" : "border-violet-200 bg-violet-50"}`}><button type="button" aria-label={`Drag ${drill.name} to reorder`} onPointerDown={(event) => startDrag(drill.id, event)} onPointerMove={(event) => updateDrag(drill.id, event)} onPointerUp={finishDrag} onPointerCancel={finishDrag} className="cursor-grab touch-none rounded p-1 text-violet-500 active:cursor-grabbing"><GripVertical className="h-5 w-5"/></button><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-violet-700 text-xs font-bold text-white">{index + 1}</span><span className="min-w-0 flex-1 truncate text-xs font-semibold">{drill.name}</span><span className="hidden items-center sm:flex"><button type="button" disabled={index === 0} onClick={() => moveDrill(index, -1)} aria-label={`Move ${drill.name} up`} className="rounded p-1 text-violet-700 disabled:opacity-25"><ArrowUp className="h-4 w-4"/></button><button type="button" disabled={index === selected.length - 1} onClick={() => moveDrill(index, 1)} aria-label={`Move ${drill.name} down`} className="rounded p-1 text-violet-700 disabled:opacity-25"><ArrowDown className="h-4 w-4"/></button></span><button type="button" onClick={() => setSelected((value) => value.filter((id) => id !== drill.id))} aria-label={`Remove ${drill.name}`} className="rounded p-1 text-danger"><X className="h-4 w-4"/></button></div>)}</div>
      <div className="relative mt-4"><Search className="absolute top-2.5 left-3 h-4 w-4 text-text-secondary"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search drills by name, tag, or description…" aria-label="Search drills for daily plan" className="h-10 w-full rounded-control border border-border pr-3 pl-9 text-xs outline-none focus:border-sky-500"/></div>
      <div className="mt-2 max-h-[23rem] space-y-2 overflow-y-auto pr-1">{drills.length === 0 ? <div className="rounded-control border border-dashed border-amber-300 bg-amber-50 p-5 text-center"><p className="text-sm font-semibold text-amber-900">Drill library unavailable</p><p className="mt-1 text-xs text-amber-800">Apply migrations 0045–0047, then refresh this page.</p></div> : availableDrills.length === 0 ? <p className="py-5 text-center text-xs text-text-secondary">No additional drills match your search.</p> : availableDrills.map((drill) => <button type="button" key={drill.id} onClick={() => setSelected((value) => [...value, drill.id])} className="flex w-full gap-3 rounded-control border border-border p-3 text-left transition hover:border-sky-300 hover:bg-sky-50"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-sky-100 text-sky-700"><Plus className="h-3.5 w-3.5"/></span><span><span className="block text-sm font-semibold">{drill.name}</span><span className="mt-0.5 block text-[11px] text-text-secondary">{drill.tags.join(" · ") || drill.category}</span></span></button>)}</div>
    </section>
  </form>;
}
