/**
 * Provenance for Rankings-era school logo assets under `public/school-logos/`.
 * Not imported by rendered UI — docs/tests only. Do not hotlink `directAssetUrl`.
 *
 * Research notes (2026-09-08):
 * - ITA/ClubSpark `td_teams.logoUrl` and organisation `profileImage` were null for
 *   these DIII teams on the fixed June 3 2026 national team list.
 * - Local athletics SVG marks were retained from Rankings workspace commit `508f94d`
 *   after exact ITA-name mapping; remote download URLs were not stored in that commit.
 * - Wikimedia Commons was checked for several schools but often returned wrong-school
 *   marks (e.g. UMass Amherst, Emory & Henry) and was not used as a substitute.
 */

export type SchoolLogoSourceType =
  | "ITA"
  | "official athletics"
  | "official brand"
  | "Wikimedia";

export type SchoolLogoManifestEntry = {
  /** Normalized ITA snapshot display name (gender suffix stripped). */
  itaDisplayName: string;
  /** Filename under `public/school-logos/`. */
  localFilename: string;
  /** Official athletics or brand page used as the research source. */
  sourcePage: string;
  /**
   * Direct remote asset URL when independently re-fetched.
   * Null when ITA had no logo and the verified local athletics mark was retained.
   */
  directAssetUrl: string | null;
  sourceType: SchoolLogoSourceType;
  /** ISO calendar date the local asset was retrieved/added. */
  retrievalDate: string;
  notes?: string;
};

const RETAINED_NOTE =
  "ITA GraphQL logoUrl/profileImage null; retained verified local athletics SVG from Rankings commit 508f94d (remote download URL not stored).";

/** Newly added Rankings coverage assets (excludes preexisting OS schedule logos). */
export const CURRENT_ITA_NEW_SCHOOL_LOGO_MANIFEST: readonly SchoolLogoManifestEntry[] = [
  {
    itaDisplayName: "University Of Chicago",
    localFilename: "chicago.svg",
    sourcePage: "https://athletics.uchicago.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Claremont-Mudd-Scripps",
    localFilename: "claremont-m-s.svg",
    sourcePage: "https://www.cmsathletics.org/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Bowdoin",
    localFilename: "bowdoin.svg",
    sourcePage: "https://athletics.bowdoin.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Swarthmore",
    localFilename: "swarthmore.svg",
    sourcePage: "https://www.swarthmoreathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Johns Hopkins",
    localFilename: "johns-hopkins.svg",
    sourcePage: "https://hopkinssports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Emory (GA)",
    localFilename: "emory.svg",
    sourcePage: "https://www.emoryathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Babson",
    localFilename: "babson.svg",
    sourcePage: "https://babsonathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Sewanee",
    localFilename: "sewanee.svg",
    sourcePage: "https://sewaneetigers.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Amherst College",
    localFilename: "amherst.svg",
    sourcePage: "https://athletics.amherst.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Middlebury",
    localFilename: "middlebury.svg",
    sourcePage: "https://athletics.middlebury.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Pomona-Pitzer",
    localFilename: "pomona-pitzer.svg",
    sourcePage: "https://www.sagehens.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Grinnell",
    localFilename: "grinnell.svg",
    sourcePage: "https://pioneers.grinnell.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Gustavus Adolphus",
    localFilename: "gust-adolphus.svg",
    sourcePage: "https://gustavus.edu/athletics/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Williams College",
    localFilename: "williams.svg",
    sourcePage: "https://ephsports.williams.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "NYU",
    localFilename: "new-york-u.svg",
    sourcePage: "https://gonyuathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Christopher Newport",
    localFilename: "chris-newport.svg",
    sourcePage: "https://cnusports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Carthage",
    localFilename: "carthage.svg",
    sourcePage: "https://athletics.carthage.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Vassar College",
    localFilename: "vassar.svg",
    sourcePage: "https://www.vassarathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Kalamazoo",
    localFilename: "kalamazoo.svg",
    sourcePage: "https://hornets.kzoo.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Wisconsin-Whitewater",
    localFilename: "wis-whitewater.svg",
    sourcePage: "https://uwwsports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Washington and Lee",
    localFilename: "wash-lee.svg",
    sourcePage: "https://generalssports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Southwestern (Texas)",
    localFilename: "southwestern-tx.svg",
    sourcePage: "https://southwesternpirates.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "North Central (IL)",
    localFilename: "north-central-il.svg",
    sourcePage: "https://northcentralcardinals.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Luther College",
    localFilename: "luther.svg",
    sourcePage: "https://norseathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "North Carolina Wesleyan University",
    localFilename: "nc-wesleyan.svg",
    sourcePage: "https://ncwcbishops.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "The College Of New Jersey",
    localFilename: "tcnj.svg",
    sourcePage: "https://tcnjlions.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Massachusetts Inst. Of Tech.",
    localFilename: "mit.svg",
    sourcePage: "https://mitathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Lake Forest",
    localFilename: "lake-forest.svg",
    sourcePage: "https://www.lakeforest.edu/athletics",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Redlands",
    localFilename: "redlands.svg",
    sourcePage: "https://goredlands.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Shenandoah",
    localFilename: "shenandoah.svg",
    sourcePage: "https://suhornets.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Haverford",
    localFilename: "haverford.svg",
    sourcePage: "https://haverfordathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Stevens Institute Of Technology",
    localFilename: "stevens.svg",
    sourcePage: "https://stevensducks.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Franklin & Marshall College",
    localFilename: "franklin-marshall.svg",
    sourcePage: "https://gofordu.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Carleton",
    localFilename: "carleton.svg",
    sourcePage: "https://apps.carleton.edu/athletics/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Bates",
    localFilename: "bates.svg",
    sourcePage: "https://athletics.bates.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Wesleyan University",
    localFilename: "wesleyan-ct.svg",
    sourcePage: "https://athletics.wesleyan.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Randolph College",
    localFilename: "randolph.svg",
    sourcePage: "https://randolphathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Ithaca",
    localFilename: "ithaca.svg",
    sourcePage: "https://athletics.ithaca.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Caltech",
    localFilename: "caltech.svg",
    sourcePage: "https://gocaltech.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Hamilton",
    localFilename: "hamilton.svg",
    sourcePage: "https://athletics.hamilton.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Ohio Northern",
    localFilename: "ohio-northern.svg",
    sourcePage: "https://onusports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Union (New York)",
    localFilename: "union-ny.svg",
    sourcePage: "https://unionathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Hope College",
    localFilename: "hope.svg",
    sourcePage: "https://athletics.hope.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Coe College",
    localFilename: "coe.svg",
    sourcePage: "https://kohawksports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Averett",
    localFilename: "averett.svg",
    sourcePage: "https://averettcougars.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Rochester (New York)",
    localFilename: "rochester-ny.svg",
    sourcePage: "https://uofrathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Rhodes",
    localFilename: "rhodes.svg",
    sourcePage: "https://rhodeslynx.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Chapman",
    localFilename: "chapman.svg",
    sourcePage: "https://athletics.chapman.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Asbury",
    localFilename: "asbury.svg",
    sourcePage: "https://asburyeagles.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Virginia Wesleyan University",
    localFilename: "va-wesleyan.svg",
    sourcePage: "https://vwumarlins.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "East Texas Baptist",
    localFilename: "east-tex-baptist.svg",
    sourcePage: "https://goetbu.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Rochester Inst. Of Tech.",
    localFilename: "rit.svg",
    sourcePage: "https://ritathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Occidental",
    localFilename: "occidental.svg",
    sourcePage: "https://oxyathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Illinois Institute Of Technology",
    localFilename: "iit.svg",
    sourcePage: "https://illinoistechathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Washington College",
    localFilename: "washington-col.svg",
    sourcePage: "https://washingtoncollegesports.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Hobart/William Smith",
    localFilename: "hobart.svg",
    sourcePage: "https://hwsathletics.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Colby College",
    localFilename: "colby.svg",
    sourcePage: "https://www.colby.edu/athletics/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Bethel (MN)",
    localFilename: "bethel-mn.svg",
    sourcePage: "https://athletics.bethel.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Mary Hardin-Baylor",
    localFilename: "mary-hardin-baylor.svg",
    sourcePage: "https://umhbcru.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Whitman College",
    localFilename: "whitman.svg",
    sourcePage: "https://athletics.whitman.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Allegheny",
    localFilename: "allegheny.svg",
    sourcePage: "https://alleghenygators.com/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
  {
    itaDisplayName: "Rose-Hulman",
    localFilename: "rose-hulman.svg",
    sourcePage: "https://athletics.rose-hulman.edu/",
    directAssetUrl: null,
    sourceType: "official athletics",
    retrievalDate: "2026-09-07",
    notes: RETAINED_NOTE,
  },
] as const;

export const CURRENT_ITA_NEW_SCHOOL_LOGO_FILENAMES =
  CURRENT_ITA_NEW_SCHOOL_LOGO_MANIFEST.map((entry) => entry.localFilename);
