-- BP-015 — Move the Team module from hard-coded data to Supabase.
--
-- Creates `production_people`: the production home for the `Person` domain
-- object (see `src/features/people/types.ts`). Column names mirror the
-- `Person` fields 1:1 (camelCase -> snake_case) so the mapping in
-- `src/features/people/supabaseMapping.ts` stays simple and obvious.
--
-- Scope note: this table only needs to support what the Team module reads
-- today (current players + alumni). It is intentionally a flat table, not
-- normalized into separate role/relationship tables yet — `docs/ARCHITECTURE.md`
-- describes a future `PersonRole` / `PersonRelationship` model, but per the
-- "add fields/objects only when a real workflow requires them" rule
-- (`docs/ARCHITECTURE.md` §19), that normalization is deferred until a
-- workflow actually needs it. `relationships` is stored as `jsonb` for now,
-- matching the always-empty-today shape already produced by the BP-012
-- import — future blueprints can migrate it to a join table without
-- changing the `Person.relationships` field consumers see.
--
-- Run this once in the Supabase SQL Editor to (re)create the table. Follow
-- it with `supabase/seed.sql` (generated by `npm run db:generate-seed` from
-- `src/features/people/data.ts`) to load the current roster.

create table if not exists public.production_people (
  -- System
  id text primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Identity
  status text not null check (status in ('current', 'alumni')),
  first_name text not null,
  middle_name text,
  last_name text not null,
  preferred_name text,
  date_of_birth date,
  photo_url text,

  -- Contact
  cell_phone text,
  personal_email text,
  denison_email text,
  preferred_contact_method text check (preferred_contact_method in ('phone', 'text', 'email')),

  -- Permanent Address
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  country text,

  -- Denison Information
  class_year integer,
  major text,
  minor text,
  denison_id text,
  dorm text,
  room_number text,

  -- Tennis Information
  utr numeric,
  wtn numeric,
  dominant_hand text check (dominant_hand in ('right', 'left')),
  height_inches integer,
  weight_lbs integer,
  player_status text check (player_status in ('active', 'injured', 'inactive', 'graduated')),

  -- Relationships (see scope note above)
  relationships jsonb not null default '[]'::jsonb,

  -- Notes
  notes text
);

comment on table public.production_people is
  'Production Person records for the Team module (BP-015). Mirrors src/features/people/types.ts Person.';

-- Keep `updated_at` accurate on every UPDATE without relying on the app to
-- remember to set it.
create or replace function public.set_production_people_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_production_people_updated_at on public.production_people;
create trigger trg_production_people_updated_at
  before update on public.production_people
  for each row
  execute function public.set_production_people_updated_at();

-- Row Level Security. The app has no authentication layer yet (see
-- `docs/ARCHITECTURE.md` §15), so for now the only credential available is
-- the shared anon/publishable key. Grant it read-only access — enough for
-- BP-015 (Team module reads) — and nothing else. Writes are deliberately
-- NOT opened up to anon; the one-time seed load happens via this same SQL
-- script (see `supabase/seed.sql`), not through the API. Revisit this policy
-- when authentication and create/update workflows (a later blueprint) land.
alter table public.production_people enable row level security;

drop policy if exists "Allow anon read access" on public.production_people;
create policy "Allow anon read access"
  on public.production_people
  for select
  to anon, authenticated
  using (true);
